name: Deploy API

on:
  workflow_dispatch:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 24
  PNPM_VERSION: 10.33.0
  INFISICAL_PROJECT_SLUG: uwdsc-54e-y
  INFISICAL_API_PATH: <api-path-here> # TODO: Update this value

jobs:
  setup:
    name: Setup Variables
    runs-on: ubuntu-latest
    outputs:
      node-version: ${{ env.NODE_VERSION }}
      pnpm-version: ${{ env.PNPM_VERSION }}
      infisical-project-slug: ${{ env.INFISICAL_PROJECT_SLUG }}
      infisical-api-path: ${{ env.INFISICAL_API_PATH }}
    steps:
      - name: Output variables
        run: echo "Variables mapped to outputs."

  build-docker:
    name: Build Docker Image
    needs: setup
    uses: uw-datasci/nexus-workflows/.github/workflows/build-docker.yml@v4
    with:
      node-version: ${{ needs.setup.outputs.node-version }}
      pnpm-version: ${{ needs.setup.outputs.pnpm-version }}
      infisical-project-slug: ${{ needs.setup.outputs.infisical-project-slug }}
      infisical-secret-path: ${{ needs.setup.outputs.infisical-api-path }}
      dockerfile: docker/Dockerfile
      docker-context: "."
      # image-tag: ${{ github.sha }}
    secrets:
      INFISICAL_CLIENT_ID: ${{ secrets.INFISICAL_CLIENT_ID }}
      INFISICAL_CLIENT_SECRET: ${{ secrets.INFISICAL_CLIENT_SECRET }}

  deploy-render:
    name: Deploy to Render
    needs: build-docker
    uses: uw-datasci/nexus-workflows/.github/workflows/deploy-render.yml@v4
    with:
      ref: ${{ github.sha }}
      service-label: API
      clear-cache: false
      wait-deploy: true
      github-deployment: false
      deployment-environment: production
    secrets:
      RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
      RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
